import type { PhaseStatus, Project } from "@/lib/types";
import type { Locale } from "@/lib/i18n";

/** Media files live in public/projects/desktop-robotic-arm/. */
const img = "/projects/desktop-robotic-arm";

/**
 * Engineering log. Facts come from the design spec of the arm
 * (docs/superpowers/specs in the Robot Arm project folder).
 *
 * 1. Phase progress is set once, here, for both languages:
 */
const status: Record<string, PhaseStatus> = {
  concept: "done",
  "mechanical-design": "in-progress",
  "joint-prototyping": "planned",
  electronics: "in-progress",
  "control-software": "planned",
  kinematics: "planned",
  assembly: "planned",
  testing: "planned",
};

/**
 * 2. To post an update, add an entry to the `updates` array of a phase,
 *    in both `en` and `it`:
 *
 *   { date: "2026-11-02", text: "First joint printed and assembled.",
 *     media: [{ kind: "image", label: "Joint 1", src: `${img}/j1.jpg`, alt: "…" }] }
 */
const shared = {
  slug: "desktop-robotic-arm",
  status: "in-development",
  coverArt: "arm",
  shareImage: `${img}/assembly-iso.jpg`,
  // cover: { kind: "cad", label: "Arm assembly", src: `${img}/cover.png`, alt: "…" },
} as const;

export const desktopRoboticArm: Record<Locale, Project> = {
  en: {
    ...shared,
    title: "6-DOF Desktop Robotic Arm",
    year: "2026 — ongoing",
    category: "Robotics · Personal Project",
    summary:
      "A six-axis desktop robot designed from scratch: mechanics, electronics, kinematics and Python control.",
    intro:
      "A personal robotic arm, designed from a blank CAD file. The goal is to own every layer of the system — structure, transmissions, electronics and control software — and to document the process as it happens. The CAD is complete: the whole model is generated by Python scripts through the Fusion API.",
    stack: ["Fusion (Python API)", "3D printing", "Python", "Kinematics", "ESP32", "ROS 2 (planned)"],
    specs: [
      { label: "Type", value: "6 axes · spherical wrist" },
      { label: "Actuators", value: "Feetech STS3215 · 12 V serial bus" },
      { label: "Reach", value: "≈ 400 mm with gripper" },
      { label: "Status", value: "CAD complete · test kit ordered" },
    ],
    objectives: [
      "Six-axis desktop robot",
      "Complete CAD design",
      "3D printed components",
      "Motors and transmissions",
      "Electronics",
      "Encoders",
      "Forward kinematics",
      "Inverse kinematics",
      "Python control",
      "Joint and Cartesian motion",
      "Future ROS 2 integration",
    ],
    timeline: [
      {
        id: "concept",
        title: "Concept",
        status: status.concept,
        summary: "Requirements, workspace, payload target and overall kinematic layout.",
        goals: ["Define requirements", "Choose the kinematic structure"],
        updates: [
          {
            date: "2026-10-07",
            text: "Requirements fixed: light pick and place, path tracing and a kinematics demonstrator. Design payload 100 g at the tool; work area an A4 sheet in front of the base.",
          },
          {
            date: "2026-10-07",
            text: "Chosen a 6R anthropomorphic layout with a spherical wrist, so the inverse kinematics has a closed form — the same structure as the KUKA robots I work on. Shoulder axis 110 mm above the table, upper arm 130 mm, forearm 130 mm.",
          },
          {
            date: "2026-10-07",
            text: "Actuators: Feetech STS3215 serial-bus servos at 12 V on every axis, with a built-in 12-bit magnetic encoder. Two on the shoulder, because a single one does not hold the required torque. Steppers with printed gearboxes were discarded for cost and for the weight at the elbow.",
          },
        ],
        media: [
          {
            kind: "image",
            label: "Build notebook — joints and link lengths",
            aspect: "3/4",
            fit: "contain",
            src: `${img}/notebook-cover.jpg`,
            alt: "Blueprint-style sketch of the six-axis arm with joints J1 to J6 labelled and link lengths 110, 130, 130 and 72 mm",
          },
        ],
      },
      {
        id: "mechanical-design",
        title: "Mechanical Design",
        status: status["mechanical-design"],
        summary: "Full CAD of links, joints and housings, designed for 3D printing.",
        goals: ["Complete CAD assembly", "Design for printability"],
        updates: [
          {
            date: "2026-10-07",
            text: "First complete assembly: base, turret, upper arm, forearm, two wrist parts and tool flange, generated by a Python script through the Fusion API. No interference with the seven joint servos in the rest pose.",
          },
          {
            date: "2026-10-08",
            text: "Restyling around the servos: 44 mm joint discs on shoulder, elbow and wrist, round covers on the two roll servos, tapered base. Free travel checked one joint at a time: J1, J4 and J6 ±180°, J2 from −100° to +105°, J5 from −95° to +130°. Of 40 random poses, 35 are collision-free; the other 5 go below the table.",
          },
          {
            date: "2026-10-08",
            text: "New parallel gripper, enclosed, inspired by the MSG gripper of the open-source PAROL6: involute pinion (module 1.5, 16 teeth) on the servo horn driving two opposed racks, each one piece with its finger. Stroke 20 mm per finger, opening 0 to 40 mm. A gravity pen holder is the alternative tool.",
          },
          {
            date: "2026-10-08",
            text: "Masses and torques recomputed on the model: about 726 g moving. With the arm stretched out and 100 g in the gripper, the shoulder needs 16.2 kg·cm (margin 1.24 on two servos), the elbow 8.5 (margin 1.17) and the wrist 3.1 (margin 3.27). The margins are below the 1.6 I aimed for: the elbow is the tightest point of the design.",
          },
          {
            date: "2026-10-09",
            text: "Still open before printing: a slicer test, and checking screw and connector positions against a real servo — for now they come from the servo's 3D model.",
          },
        ],
        media: [
          {
            kind: "cad",
            label: "Assembly — isometric view",
            aspect: "1/1",
            src: `${img}/assembly-iso.jpg`,
            alt: "Line drawing of the complete arm: tapered base, two links with round joint covers and a parallel gripper",
          },
          {
            kind: "cad",
            label: "Assembly — side view",
            aspect: "1/1",
            src: `${img}/assembly-side.jpg`,
            alt: "Side view of the arm with the upper arm vertical and the forearm horizontal",
          },
          {
            kind: "cad",
            label: "Parallel gripper",
            aspect: "1/1",
            src: `${img}/gripper.jpg`,
            alt: "Line drawing of the enclosed gripper with two wedge-shaped fingers",
          },
        ],
      },
      {
        id: "joint-prototyping",
        title: "Joint Prototyping",
        status: status["joint-prototyping"],
        summary:
          "First on the bench: one servo with the test kit, to measure real dimensions, backlash and torque before printing the joint.",
        goals: ["Measure the servo and its backlash", "Print and test the shoulder joint"],
        updates: [],
      },
      {
        id: "electronics",
        title: "Electronics",
        status: status.electronics,
        summary: "Servo bus, controller board, emergency stop, power and wiring.",
        goals: ["Bus adapter and controller", "Emergency stop"],
        updates: [
          {
            date: "2026-10-09",
            text: "Architecture decided: a Waveshare bus servo adapter driven over UART by an ESP32-C3 board, which bridges the computer and the servos and reads an emergency-stop button on a normally-closed contact. When it is pressed, the servos stop and hold their position.",
          },
          {
            date: "2026-10-09",
            text: "Test kit ordered: one servo, the adapter, two ESP32-C3 boards, a 12 V 5 A power supply and the stop button. It will prove the electronics, the real servo dimensions and the backlash before the other seven servos are bought.",
          },
        ],
      },
      {
        id: "control-software",
        title: "Control Software",
        status: status["control-software"],
        summary: "Bridge firmware for the ESP32 and a Python layer for commanding joints and reading feedback.",
        goals: ["ESP32 bridge firmware", "Python control interface"],
        updates: [],
      },
      {
        id: "kinematics",
        title: "Kinematics",
        status: status.kinematics,
        summary: "Forward and inverse kinematics, then Cartesian motion.",
        goals: ["Forward kinematics", "Inverse kinematics", "Cartesian moves"],
        updates: [],
      },
      {
        id: "assembly",
        title: "Assembly",
        status: status.assembly,
        summary: "All six axes printed, assembled and wired.",
        updates: [],
      },
      {
        id: "testing",
        title: "Testing",
        status: status.testing,
        summary: "Motion tests, repeatability checks and a path towards ROS 2.",
        goals: ["Motion tests", "ROS 2 integration"],
        updates: [],
      },
    ],
  },

  it: {
    ...shared,
    title: "Braccio robotico desktop a 6 assi",
    year: "2026 — in corso",
    category: "Robotica · Progetto personale",
    summary:
      "Un robot desktop a sei assi progettato da zero: meccanica, elettronica, cinematica e controllo in Python.",
    intro:
      "Un braccio robotico personale, progettato partendo da un file CAD vuoto. L’obiettivo è padroneggiare ogni livello del sistema — struttura, trasmissioni, elettronica e software di controllo — e documentare il processo mentre avviene. Il CAD è completo: l’intero modello è generato da script Python tramite le API di Fusion.",
    stack: ["Fusion (API Python)", "Stampa 3D", "Python", "Cinematica", "ESP32", "ROS 2 (previsto)"],
    specs: [
      { label: "Tipo", value: "6 assi · polso sferico" },
      { label: "Attuatori", value: "Feetech STS3215 · bus seriale 12 V" },
      { label: "Sbraccio", value: "≈ 400 mm con pinza" },
      { label: "Stato", value: "CAD completo · kit di prova ordinato" },
    ],
    objectives: [
      "Robot desktop a sei assi",
      "Progettazione CAD completa",
      "Componenti stampati in 3D",
      "Motori e trasmissioni",
      "Elettronica",
      "Encoder",
      "Cinematica diretta",
      "Cinematica inversa",
      "Controllo tramite Python",
      "Movimenti joint e cartesiani",
      "Futura integrazione ROS 2",
    ],
    timeline: [
      {
        id: "concept",
        title: "Concept",
        status: status.concept,
        summary: "Requisiti, area di lavoro, carico utile e schema cinematico generale.",
        goals: ["Definire i requisiti", "Scegliere la struttura cinematica"],
        updates: [
          {
            date: "2026-10-07",
            text: "Requisiti fissati: pick and place leggero, tracciatura di percorsi e dimostratore di cinematica. Carico di progetto 100 g all’utensile; area di lavoro un foglio A4 davanti alla base.",
          },
          {
            date: "2026-10-07",
            text: "Scelto uno schema 6R antropomorfo con polso sferico, così la cinematica inversa ha una soluzione in forma chiusa: è la stessa struttura dei robot KUKA su cui lavoro. Asse della spalla a 110 mm dal piano, braccio 130 mm, avambraccio 130 mm.",
          },
          {
            date: "2026-10-07",
            text: "Attuatori: servo Feetech STS3215 a bus seriale, 12 V, su tutti gli assi, con encoder magnetico a 12 bit integrato. Due sulla spalla, perché uno solo non regge la coppia richiesta. Scartati gli stepper con riduttori stampati, per costo e per il peso al gomito.",
          },
        ],
        media: [
          {
            kind: "image",
            label: "Taccuino di costruzione — giunti e quote",
            aspect: "3/4",
            fit: "contain",
            src: `${img}/notebook-cover.jpg`,
            alt: "Schizzo in stile blueprint del braccio a sei assi con i giunti da J1 a J6 e le quote 110, 130, 130 e 72 mm",
          },
        ],
      },
      {
        id: "mechanical-design",
        title: "Progettazione meccanica",
        status: status["mechanical-design"],
        summary: "CAD completo di link, giunti e carter, pensato per la stampa 3D.",
        goals: ["Assieme CAD completo", "Progettare per la stampa"],
        updates: [
          {
            date: "2026-10-07",
            text: "Primo assieme completo: base, torretta, braccio, avambraccio, due pezzi del polso e flangia utensile, generati da uno script Python tramite le API di Fusion. Nessuna interferenza con i sette servo dei giunti in posa di riposo.",
          },
          {
            date: "2026-10-08",
            text: "Restyling attorno ai servo: dischi di giunto da 44 mm su spalla, gomito e polso, carter tondi sui due servo di rollio, base rastremata. Corse libere verificate un giunto alla volta: J1, J4 e J6 ±180°, J2 da −100° a +105°, J5 da −95° a +130°. Su 40 pose casuali, 35 sono senza collisioni; le altre 5 scendono sotto il piano del tavolo.",
          },
          {
            date: "2026-10-08",
            text: "Nuova pinza parallela, chiusa, ispirata alla pinza MSG del PAROL6 open source: pignone a evolvente (modulo 1,5, 16 denti) sulla squadretta del servo, che muove due cremagliere opposte, ognuna in un pezzo unico con il suo dito. Corsa 20 mm per dito, apertura da 0 a 40 mm. L’utensile alternativo è un portapenna a gravità.",
          },
          {
            date: "2026-10-08",
            text: "Masse e coppie ricalcolate sul modello: circa 726 g in movimento. A braccio disteso con 100 g in presa, la spalla richiede 16,2 kg·cm (margine 1,24 su due servo), il gomito 8,5 (margine 1,17) e il polso 3,1 (margine 3,27). I margini sono sotto l’1,6 che mi ero dato: il gomito è il punto più tirato del progetto.",
          },
          {
            date: "2026-10-09",
            text: "Ancora da fare prima di stampare: la prova nello slicer e il controllo di viti e connettori su un servo reale; per ora vengono dal modello 3D del servo.",
          },
        ],
        media: [
          {
            kind: "cad",
            label: "Assieme — vista isometrica",
            aspect: "1/1",
            src: `${img}/assembly-iso.jpg`,
            alt: "Disegno a tratto del braccio completo: base rastremata, due link con carter tondi sui giunti e pinza parallela",
          },
          {
            kind: "cad",
            label: "Assieme — vista laterale",
            aspect: "1/1",
            src: `${img}/assembly-side.jpg`,
            alt: "Vista laterale del braccio con il braccio verticale e l’avambraccio orizzontale",
          },
          {
            kind: "cad",
            label: "Pinza parallela",
            aspect: "1/1",
            src: `${img}/gripper.jpg`,
            alt: "Disegno a tratto della pinza chiusa con due dita a cuneo",
          },
        ],
      },
      {
        id: "joint-prototyping",
        title: "Prototipo del giunto",
        status: status["joint-prototyping"],
        summary:
          "Per prima cosa sul banco: un servo con il kit di prova, per misurare dimensioni reali, gioco e coppia prima di stampare il giunto.",
        goals: ["Misurare il servo e il suo gioco", "Stampare e provare il giunto della spalla"],
        updates: [],
      },
      {
        id: "electronics",
        title: "Elettronica",
        status: status.electronics,
        summary: "Bus dei servo, scheda di controllo, arresto di emergenza, alimentazione e cablaggio.",
        goals: ["Adattatore del bus e controllore", "Arresto di emergenza"],
        updates: [
          {
            date: "2026-10-09",
            text: "Architettura decisa: un adattatore Waveshare per servo a bus seriale, comandato via UART da una schedina ESP32-C3 che fa da tramite tra computer e servo e legge un fungo di arresto su un contatto normalmente chiuso. Quando viene premuto, i servo si fermano e tengono la posizione.",
          },
          {
            date: "2026-10-09",
            text: "Ordinato il kit di prova: un servo, l’adattatore, due schedine ESP32-C3, un alimentatore 12 V 5 A e il fungo di arresto. Servirà a provare l’elettronica, le dimensioni reali del servo e il gioco prima di comprare gli altri sette servo.",
          },
        ],
      },
      {
        id: "control-software",
        title: "Software di controllo",
        status: status["control-software"],
        summary: "Firmware ponte per l’ESP32 e livello Python per comandare i giunti e leggere il feedback.",
        goals: ["Firmware ponte per l’ESP32", "Interfaccia di controllo Python"],
        updates: [],
      },
      {
        id: "kinematics",
        title: "Cinematica",
        status: status.kinematics,
        summary: "Cinematica diretta e inversa, poi movimento cartesiano.",
        goals: ["Cinematica diretta", "Cinematica inversa", "Movimenti cartesiani"],
        updates: [],
      },
      {
        id: "assembly",
        title: "Assemblaggio",
        status: status.assembly,
        summary: "Tutti e sei gli assi stampati, assemblati e cablati.",
        updates: [],
      },
      {
        id: "testing",
        title: "Test",
        status: status.testing,
        summary: "Prove di movimento, verifiche di ripetibilità e percorso verso ROS 2.",
        goals: ["Prove di movimento", "Integrazione ROS 2"],
        updates: [],
      },
    ],
  },
};
